---
replicaCount: 1

crds:
  create: true

monitoring:
  podMonitorEnabled: true
  grafanaDashboard:
    create: true
    namespace: monitoring

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    memory: 500Mi
